apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: codegen-manual-testing-llamacpp-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tpetkos/codegen-manual-testing-llamacpp-1:6112cd479b7444330b370fa8c9e2300671ccefbb@sha256:179510fd2cd317fcf3c0cc074dd43440fabffe7e25c1c52d1c9a26e0bf4e6af6 # use pre-built to bootstrap 
          name: app-inference
