---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: codegen-manual-testing-llamacpp-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codegen-manual-testing-llamacpp-1 
  name: codegen-manual-testing-llamacpp-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi